/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=admin/wrangler.jsonc --include-runtime=false --strict-vars=false admin/worker-configuration.d.ts` (hash: f7b988cda0f47071ae9389a03e20de53)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ADMIN_ORIGIN: string;
	ACCESS_ISSUER: string;
	ACCESS_AUD: string;
	ADMIN_EMAILS: string;
	GITHUB_REPOSITORY: string;
	PUBLISH_ENABLED: string;
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_ORIGIN" | "ACCESS_ISSUER" | "ACCESS_AUD" | "ADMIN_EMAILS" | "GITHUB_REPOSITORY" | "PUBLISH_ENABLED" | "GITHUB_TOKEN">> {}
}
